### ISSUE TITLE
Does this work with any popular VPN providers?

### ISSUE THREAD

**Issue by subdavis** [SebDanielsson/compose-transmission-wireguard#1]
Possibly worth documenting.  Many VPN providers allow WireGuard, such as PIA.  Will this work, or not because they don't provide connection details and hide it all in an app.

**Comment by sebdanielsson** [comment]
Personally I'm using Mullvad.net which offers an excellent configurator and has a great reputation for it's privacy and security measures. I open to add a table with VPN providers that offers a VPN connection over the standard WireGuard app but I think we need to come up with at least two more providers.

**Comment by Elliptic1503** [comment]
Windscribe, Keepsolid and AzireVPN offer WireGuard configuration downloads, in addition to Mullvad.

Edit: I can see that GL-iNet provide a list of other companies which allow downloads of WireGuard conf files:
https://docs.gl-inet.com/en/3/app/wireguard/#wireguard-providers

**Comment by sebdanielsson** [comment]
> Windscribe, Keepsolid and AzireVPN offer WireGuard configuration downloads, in addition to Mullvad.
> 
> Edit: I can see that GL-iNet provide a list of other companies which allow downloads of WireGuard conf files:
> https://docs.gl-inet.com/en/3/app/wireguard/#wireguard-providers

Thanks! Any idea which of these services also offers port forwarding? I know Mullvad do and it really helps increasing download speeds.

**Comment by Elliptic1503** [comment]
> Thanks! Any idea which of these services also offers port forwarding? I know Mullvad do and it really helps increasing download speeds.

Windscribe offers ephemeral port forwarding, requiring re-registration every 24 hours (I guess it could be scripted).  They allow for permanent port forwarding with static IP's which cost more, but might defeat the purpose of using a VPN. 

https://blog.windscribe.com/port-forwarding-static-ips-and-lies-bcf427fdb283

Other than that I don't know of others that have it (wasn't even aware Mullvad offered it).

**Comment by sebdanielsson** [comment]
> > Thanks! Any idea which of these services also offers port forwarding? I know Mullvad do and it really helps increasing download speeds.
> 
> Windscribe offers ephemeral port forwarding, requiring re-registration every 24 hours (I guess it could be scripted). They allow for permanent port forwarding with static IP's which cost more, but might defeat the purpose of using a VPN.
> 
> https://blog.windscribe.com/port-forwarding-static-ips-and-lies-bcf427fdb283
> 
> Other than that I don't know of others that have it (wasn't even aware Mullvad offered it).

I've added a list to the readme. Thanks for the link, if you find any more providers that fits the criteria that's specified above the comparison table feel free to send in a PR! :)
