### ISSUE TITLE
WG and Transmission Not Connecting to One Another After Update

### ISSUE THREAD

**Issue by SteffanCline** [SebDanielsson/compose-transmission-wireguard#10]
I recently ran into an issue where I deleted the containers and pulled the latest versions. All the configs and all stayed the same but the two are not talking. I am 100% positive that I took the IP from the wg0.conf and put it into the transmission config. That is the only thing configuration-wise would have failed. I'm still a novice with Docker. Where are the log files for these containers located on Ubuntu? Any suggestions of what to check for? 

```
CONTAINER ID   IMAGE                              COMMAND                  CREATED        STATUS        PORTS                                                  NAMES
ccb3739fbb97   ghcr.io/linuxserver/transmission   "/init"                  21 hours ago   Up 21 hours                                                          transmission
62b28fbbb2b9   ghcr.io/linuxserver/wireguard      "/init"                  21 hours ago   Up 21 hours   0.0.0.0:9091->9091/tcp, :::9091->9091/tcp, 51820/udp   wireguard
```

**Comment by SteffanCline** [comment]
While waiting, I renamed the directory to .bak and redownloaded everything from scratch and got it working again but what would have caused that and where would the log files be for both wireguard and transmission to debug that next time?

**Comment by sebdanielsson** [comment]
Did you use docker compose to bring down the containers and re-create them or did you manually stop and delete the containers with docker container stop and docker container rm? If you used docker compose for creation and deletion, the transmission and wireguard containers should be on the same network and *should* be able to communicate.
