### ISSUE TITLE
Accessing the dashboard outside of the VPN

### ISSUE THREAD

**Issue by gio-giorgio** [SebDanielsson/compose-transmission-wireguard#12]
Hi,

I have a server (location A) where I use compose-transmission-wireguard, with the VPN pointing to a Raspberry Pi (location B).

My issue is that the transmission dashboard is only accessible when I am connected to the VPN, and I would like to be able to use it in location A. I also want in the future to add radarr and lidarr, also accessible on location A without being connected to the VPN.

Is that possible?

**Comment by sebdanielsson** [comment]
Hi! There are many ways to solve this.

To access the WebUI from any device I would use Tailscale on your client device and the server. It still requires you to be connected via Tailscale's "VPN" app but only the traffic routed to your server would be sent through it. It's probably the most secure solution since it won't be accessible on the public internet.

If you really don't want to use a VPN you could use a reverse proxy on your server. Traefik is a great Docker solution but NGINX and Caddy are solid choices too. If you proceed with Traefik you just need to make sure Traefik, wireguard and transmission are on a shared network and add these labels to your transmission-wireguard compose file:

```
labels:
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.yourdomain.com`)
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.http.routers.transmission.tls.certresolver=letsencrypt
      - traefik.http.routers.transmission.middlewares=transmission-auth
      - traefik.http.middlewares.transmission-auth.basicauth.users=yourusername:yourpassword
```

Note that you need to hash the password when using basicauth:
https://doc.traefik.io/traefik/middlewares/http/basicauth/

**Comment by gio-giorgio** [comment]
Hi! First of all, thank you for your reply!

I have been seeing some traefik tutorials, but I get a bit confused because I am not interested in adding my own domain, and I don't want to expose it to the internet. As it is my understanding, I want to avoid passing through the interface through the VPN.

I also found someone that modified their wg0.conf for the same purpose, but instead of Transmission they used Deluge:

`PostUp = DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route add $HOMENET3 via $DROUTE;ip route add $HOMENET2 via $DROUTE; ip route add $HOMENET via $DROUTE;iptables -I OUTPUT -d $HOMENET -j ACCEPT;iptables -A OUTPUT -d $HOMENET2 -j>PreDown = HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route del $HOMENET3 via $DROUTE;ip route del $HOMENET2 via $DROUTE; ip route del $HOMENET via $DROUTE; iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT; iptables -D OUTPUT ->`

**Comment by sebdanielsson** [comment]
Just a quick update. I found this helpful resource.
https://www.linuxserver.io/blog/routing-docker-host-and-container-traffic-through-wireguard

Will take a look and update the documentation👍

**Comment by gio-giorgio** [comment]
Hi! Thank you again for helping in this matter.

I followed this guide: https://docs.linuxserver.io/images/docker-wireguard

_When routing via Wireguard from another container using the service option in docker, you might lose access to the containers webUI locally. To avoid this, exclude the docker subnet from being routed via Wireguard by modifying your wg0.conf like so (modifying the subnets as you require):_

`[Interface]
PrivateKey = <private key>
Address = 9.8.7.6/32
DNS = 8.8.8.8
PostUp = DROUTE=$(ip route | grep default | awk '{print $3}'); HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route add $HOMENET3 via $DROUTE;ip route add $HOMENET2 via $DROUTE; ip route add $HOMENET via $DROUTE;iptables -I OUTPUT -d $HOMENET -j ACCEPT;iptables -A OUTPUT -d $HOMENET2 -j ACCEPT; iptables -A OUTPUT -d $HOMENET3 -j ACCEPT;  iptables -A OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT
PreDown = HOMENET=192.168.0.0/16; HOMENET2=10.0.0.0/8; HOMENET3=172.16.0.0/12; ip route del $HOMENET3 via $DROUTE;ip route del $HOMENET2 via $DROUTE; ip route del $HOMENET via $DROUTE; iptables -D OUTPUT ! -o %i -m mark ! --mark $(wg show %i fwmark) -m addrtype ! --dst-type LOCAL -j REJECT; iptables -D OUTPUT -d $HOMENET -j ACCEPT; iptables -D OUTPUT -d $HOMENET2 -j ACCEPT; iptables -D OUTPUT -d $HOMENET3 -j ACCEPT`

Now I have access to the web UI in both locations. I believe that the public traffic (as in, the actual torrents) still goes through the VPN.

**Comment by sebdanielsson** [comment]
This was actually pretty straight forward.

Just add the following to your wg0.conf and local traffic should be allowed to bypass the VPN.
```
PostUp = ip route add 192.168.1.0/24 via 172.100.0.1;
PreDown = ip route delete 192.168.1.0/24;
```

This example assume that the client accessing the WebUI is on the subnet 192.168.1.0. If you want to access the WebUI through your VPN you can change the subnet to the VPNs subnet.

Edit: Completely missed your reply. Nice find!😃

**Comment by beren12** [comment]
Could you add this last tip to the readme? took me forever to figure out accessing the port from my lan machines.

**Comment by paynd** [comment]
> This was actually pretty straight forward.
> 
> Just add the following to your wg0.conf and local traffic should be allowed to bypass the VPN.
> 
> ```
> PostUp = ip route add 192.168.1.0/24 via 172.100.0.1;
> PreDown = ip route delete 192.168.1.0/24;
> ```
> 
> This example assume that the client accessing the WebUI is on the subnet 192.168.1.0. If you want to access the WebUI through your VPN you can change the subnet to the VPNs subnet.
> 
> Edit: Completely missed your reply. Nice find!😃

It helped me. Thanks.

**Comment by sebdanielsson** [comment]
> Could you add this last tip to the readme? took me forever to figure out accessing the port from my lan machines.

Sorry for the late reply. I will add it to the readme!
