### ISSUE TITLE
Changing bind-address-ipv4 and bind-address-ipv6 to Mullvad's server addresses stops any connection

### ISSUE THREAD

**Issue by gitrmarx** [SebDanielsson/compose-transmission-wireguard#13]
If I change `bind-address-ipv4` and `bind-address-ipv6` to Mullvad's server IP addresses, I can't download anything. With these settings at the defaults of `"0.0.0.0"` and `"::"`, if I test my connection using [this](http://checkmyip.torrentprivacy.com/), I can see that the IP address of my torrenting belongs to Mullvad, as expected. But when I change them to Mullvad's public address, I can't even get an IP out of the website.

Using for example this server:
![image](https://user-images.githubusercontent.com/74657459/176809195-ba82e468-e49b-4c0f-b764-720ddc1d2e1d.png)

My config should (at least from what I understand) look like this:
```
"bind-address-ipv4": "138.199.6.194",
"bind-address-ipv6": "2a02:6ea0:d406:1::a18f",
```

I have changed settings.json only while the containers were stopped. Please let me know if you need any logs or something. Thanks!

**Comment by sebdanielsson** [comment]
Sorry for the very late response! The IP should be the local IP given from your VPN provider. I've clarified this in the readme now.

**Comment by gitrmarx** [comment]
Oh, that makes sense. Thanks!
