### ISSUE TITLE
Verify port forwarding is working

### ISSUE THREAD

**Issue by constantins2001** [SebDanielsson/compose-transmission-wireguard#14]
Currently using the new WireGuard offering from ProtonVPN.

The log output shows ``initnatpmp`` succeeding, but my ``Port forwarding state`` stays at ``???``.
How would one verify port forwarding is working?

![2022-12-23_17-08](https://user-images.githubusercontent.com/53787471/209365209-96e133a9-a135-4ecd-9925-82f8002a818b.png)

**Comment by sebdanielsson** [comment]
Hi! First of all sorry for the late reply. I've been pretty busy over the holidays with school and work.

Currently using Mullvad as my primary VPN provider. I just tried to create a WireGuard config file for ProtonVPN but it seems that you can only enable NAT-PMP and not get a fixed port to configure Transmission with. Is this correct?

I guess the only thing you can do is to enable NAT-PMP in the Transmission settings. Have you tried that?
