### ISSUE TITLE
Transmission stops working when watchtower updates Wireguard

### ISSUE THREAD

**Issue by gio-giorgio** [SebDanielsson/compose-transmission-wireguard#15]
I am having an issue that anytime Watchtower updates Wireguard, Transmission stops working until I restart it.

I made these changes to the compose.yml file, in the Transmission section:

`
network_mode: "service:wireguard"
    depends_on: ["wireguard"]
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.depends-on: wireguard
`

Also tried to run the compose file with `docker-compose -up -d --always-recreate-deps`. But still it doesn't work. Any ideas?

**Comment by sebdanielsson** [comment]
I had the same issue with Watchtower and only when updating the WireGuard container. Unfortunately I never found a solution so I'm managing the updates of these containers manually now.
