### ISSUE TITLE
Configuring for PIA

### ISSUE THREAD

**Issue by dlecan** [SebDanielsson/compose-transmission-wireguard#18]
Hello,

I used to work with Mullvad port forwarding, but they will stop supporting it soon.
has anyone manage to configure this project with PIA ?

**Comment by sebdanielsson** [comment]
> Hello,
> 
> 
> 
> I used to work with Mullvad port forwarding, but they will stop supporting it soon.
> 
> has anyone manage to configure this project with PIA ?

This link can be found in the repo.

https://helpdesk.privateinternetaccess.com/kb/articles/manual-connection-and-port-forwarding-scripts-for-linux

Have you followed it?

**Comment by dlecan** [comment]
Not yet
It’s much more complex than for Mullvad and the config you did in this repo 😅
I think I will first try a 3rd party tool: https://github.com/jdelkins/pia-tools

**Comment by sebdanielsson** [comment]
If you find a simple solution I’d be happy to link to this issue with the solution.

**Comment by sebdanielsson** [comment]
For those using ProtonVPN and want to open port there is now a Docker mod to achieve this.
https://github.com/jordanpotter/docker-mods
