### ISSUE TITLE
Transmission Upgrade

### ISSUE THREAD

**Issue by SteffanCline** [SebDanielsson/compose-transmission-wireguard#19]
Can you please update the version of Transmission? According to their page, it's up to 4.03 but in the docker console, it shows server version 3.0.0

**Comment by sebdanielsson** [comment]
Totally forgot about that one. Should be fixed now. Thanks for the reminder!☺️

**Comment by SteffanCline** [comment]
Do I just need to delete the containers and git clone all over again to grab the latest?

**Comment by sebdanielsson** [comment]
Git clone and then run:

```
docker compose pull
docker compose up -d
```

Then you should be on the latest version👍

**Comment by sebdanielsson** [comment]
Or just edit the compose file yourself and run the commands above. Otherwise you might overwrite the config.

**Comment by SteffanCline** [comment]
<img width="532" alt="image" src="https://github.com/sebdanielsson/compose-transmission-wireguard/assets/1323544/1e324e37-9a58-455d-bb0b-73ea9a470fe0">

I see that defined in the ENV of the compose.yaml. What does this mean?

**Comment by SteffanCline** [comment]
Taking out TRANSMISSION_WEB_HOME=/transmissionic/ worked however now I just have the really old school look, not the new transmissionic. Is the path for that wrong in this new image?

**Comment by sebdanielsson** [comment]
The LinuxServer guys has stopped bundling 3rd party themes in their images. You'll need to add the the to the config path and configure it by yourself.

This might be helpful😃
https://forum.allenscloud.com/t/transmission-4-0-0-3rd-party-web-ui-options-and-install/61
