### ISSUE TITLE
Changing wg0 file name.

### ISSUE THREAD

**Issue by GenesisAdam** [SebDanielsson/compose-transmission-wireguard#4]
I want to connect the wireguard as client to an existing server and it requires me to change the wg0.conf file name to something different like cityvpn.conf but the container is failing to pick up the conf file as shown in this error message:

**_No client conf found. Provide your own client conf as "/config/wg0.conf" and restart the container. ****_**

Is there a way of changing the /config/wg0.conf to /config/cityvpn.conf inside the container?
Many thanks for your help.

**Comment by sebdanielsson** [comment]
Sorry for the very slow answer. I've been pretty busy with school and other stuff.

Maybe you could solve it with a bind mount? Like this?
`./config/cityvpn.conf:/config/wg0.conf`

**Comment by master-hax** [comment]
alternatively `docker exec -it wireguard-container mv /config/cityvpn.con /config/wg0.conf`

**Comment by master-hax** [comment]
alternatively `docker exec -it wireguard-container mv /config/cityvpn.conf /config/wg0.conf`

**Comment by GenesisAdam** [comment]
> alternatively `docker exec -it wireguard-container mv /config/cityvpn.conf /config/wg0.conf`

Many thanks for your suggestion. The wireguard is working without any error messages after running the sugested mv command but I try to test the Transmission with a manual download of a torrent but I get the error message:

Honeyland.2019.WEB.h264-W4F[TGx] Scrape error: Could not connect to tracker (/home/buildozer/aports/community/transmission/src/transmission-3.00/libtransmission/announcer.c:1392)

Any ideas as to why?

**Comment by master-hax** [comment]
what is the output of `docker exec -it transmission-container curl api.ipify.org`?

**Comment by master-hax** [comment]
does `docker exec -it transmission-container curl api.ipify.org` correctly output your VPN's exit IP address?

**Comment by GenesisAdam** [comment]
> does `docker exec -it transmission-container curl api.ipify.org` correctly output your VPN's exit IP address?

I ran that and got the message:

curl: (6) Could not resolve host: api.ipify.org

**Comment by GenesisAdam** [comment]
The issue has been resolved using the suggestion contained in the blog posted [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiPt8qBuaz1AhVIZMAKHQOCAnAQFnoECBEQAQ&url=http%3A%2F%2Fveritaspericias.com%2F5xx6wd%2Fwireguard-docker-setup.html&usg=AOvVaw0CZKy8wqIVvHLHRKcmFVDu). Now transmission is connecting to the internet via wireguard and downloading torrents. Many thanks for all your help.

**Comment by sebdanielsson** [comment]
Awesome, take care!
