### ISSUE TITLE
verification

### ISSUE THREAD

**Issue by cirrusflyer** [SebDanielsson/compose-transmission-wireguard#6]
Is there a way to verify that the container traffic is actually flowing through the Wireguard tunnel?  In my case I'm using Mullvad.  I recall a couple years ago a way to check this with Mullvad, but can't seem to find it now.  Also, can you elaborate on the IP address used for the kill switch?  If it's my external IP, which is dynamic, that would be an issue.  Or can one use a FQDN that's tied to a DDNS?

Thanks

**Comment by sebdanielsson** [comment]
If you don't want your public IP to get leaked I would use the transmission config to bind all Transmission communication to the VPN public IP. That way your public IP won't leak if the VPN connection breaks.

The Mullvad connection checks are available here:
https://mullvad.net/check/

**Comment by cirrusflyer** [comment]
Thanks.  I know about those Mullvad checks, but there's no way to check to see if the docker container is using the VPN,  I recall some kind of test using a test torrent or something. Just can't find it.

**Comment by cirrusflyer** [comment]
I found this that allows a test.  https://ipleak.net

**Comment by juanra** [comment]
> 

Seb, can you elaborate a bit on the killswitch config please.  The public IP of the VPN does not change by region or every time you connect? How do I know which IP you should include in the transmission settings.

**Comment by sebdanielsson** [comment]
The public IP is, at least in the case of Mullvad, the same as your WireGuard endpoint IP. The IP may change from time to time but it's never happened to me and I've running this config for a couple of years. But I guess it varies from provider to provider. Every VPN server uses a different public IP address.
