### ISSUE TITLE
Config Questions

### ISSUE THREAD

**Issue by SteffanCline** [SebDanielsson/compose-transmission-wireguard#7]
I'm new to docker so I'm hoping for a little help. I updated the settings.json file inside to match the non-docker transmission I've been using. I'd think that this would be all the settings I need but when I did the docker compose, it created the downloads and watch folders. Do those paths from the configure.yaml file override what's in the settings.json file?

Also, are these supposed to the user/group that transmission runs as?
```
PUID=1000 
PGID=1000
```
You covered most of the directories but there's one for incomplete that wasn't in the list. In my settings.json file I have these
```
"incomplete-dir": "/storage/Downloaders/Transmission/incomplete",
"download-dir": "/storage/Downloaders/Complete",
"watch-dir": "/storage/Downloaders/Media-DropBox"
```
Would simply adding the directory to the compose.yaml solve that or will it just work from the settings.json file?
```- /storage/Downloaders/Transmission/incomplete:/incomplete```

Same thing for blocklist. Does it require a parameter or will it just use this from the config file?
```"blocklist-url": "https://github.com/Naunter/BT_BlockLists/raw/master/bt_blocklists.gz"```

Same question for ```umask```. Will it honor the setting in settings.json?

**Comment by sebdanielsson** [comment]
You should leave the paths in settings.json and only change the path in your compose file. The path on the right side of the bind mount need to patch the location in settings.json and is only for the container process. The path on the left side of the bind mount inside your compose file is where you'll find the files on your host system.

I've not actually checked if the umask settings is preserved to the host system but I believe it should be.
